POST http://localhost:8080/admin HTTP/1.1
Content-Type: application/json

{
	"intra_id": "jinkim",
	"nickname": "jinkimnick",
	"auth_token" : "sayi@@mail",
	"icon" : "sayi is sayi",
	"friend_list": ["taekkim", "jinkim"]
}

# PATCH http://localhost:8080/admin HTTP/1.1
# Content-Type: application/json

# {
# 	"intra_id": "taekim",
# 	"nickname": "taekimnick",
# 	"auth_token" : "sayi@@mail",
# 	"icon" : "sayi is sayi",
# 	"friend_list": ["taekkim"]
# }

# DELETE http://localhost:8080/admin/clear HTTP/1.1

# GET http://localhost:8080/admin/all HTTP/1.1

