POST http://localhost:8080/match-history HTTP/1.1
Content-Type: application/json

{
	"p1_id": "sayi",
	"p2_id": "taekim",
	"winner" : "taekim"
}

# DELETE http://localhost:8080/match-history/clear HTTP/1.1

# GET http://localhost:8080/match-history/findMatchHistrory HTTP/1.1

