# GET http://localhost:8080/profile?myID=jinkimNick&otherID=jinkimNick HTTP/1.1
#GET http://localhost:8080/profile/allblock?myID=safd HTTP/1.1

PATCH http://localhost:8080/profile/userState
Content-Type: application/json

{
	"id": "minami",
	"state": "off"
}

#PUT http://localhost:8080/profile/friend HTTP/1.1
#Content-Type: application/json
#
#{
#	"myID":"jinkimnick",
#	"otherID":"taekimnick"
#}

# PUT http://localhost:8080/profile/block HTTP/1.1
# Content-Type: application/json

# {
# 	"myID":"tak",
# 	"otherID":"jin",
# 	"isBlock":false
# }

# GET http://localhost:8080/profile HTTP/1.1
# GET http://localhost:8080/profile/all HTTP/1.1


